/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.forms.dialogs.register;

import static java.awt.SystemColor.control;
import javax.swing.JOptionPane;
import controllers.CustomerController;
import controllers.VehicleController;
import modelo.domain.Customer;
import modelo.domain.Vehicle;
import modelo.util.IconManager;
import modelo.util.Validator;
import org.kordamp.ikonli.bootstrapicons.BootstrapIcons;
import org.kordamp.ikonli.boxicons.BoxiconsRegular;
import org.kordamp.ikonli.carbonicons.CarbonIcons;
import org.kordamp.ikonli.dashicons.Dashicons;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author drola
 */
public class RegisVehicle extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisVehicle.class.getName());

    private VehicleController controll = new VehicleController();
    private Customer clienteSeleccionado;

    /**
     * Creates new form RegisterCustomerr
     */
    public RegisVehicle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        injectIcons();

    }

    public void injectIcons() {
        IconManager.setIkonliIcon(lblName, BootstrapIcons.FILE_PERSON, 25);
        IconManager.setIkonliIcon(lblLastName, BootstrapIcons.FILE_PERSON_FILL, 25);
        IconManager.setIkonliIcon(lblGas, CarbonIcons.GAS_STATION, 25);
        IconManager.setIkonliIcon(lblMapGas, BoxiconsRegular.MAP, 25);
        IconManager.setIkonliIcon(lblPhoneç, BootstrapIcons.TELEPHONE, 25);
        IconManager.setIkonliIcon(lblRuc, Dashicons.MEDIA_DOCUMENT, 25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtManufacturer = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblPhoneç = new javax.swing.JLabel();
        txtPurchaseDate = new javax.swing.JTextField();
        lblGas = new javax.swing.JLabel();
        txtPlate = new javax.swing.JTextField();
        lblRuc = new javax.swing.JLabel();
        txtCapMax = new javax.swing.JTextField();
        lblMapGas = new javax.swing.JLabel();
        txtFuel = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnInsertVehicle = new javax.swing.JButton();
        lblName1 = new javax.swing.JLabel();
        lblMapGas1 = new javax.swing.JLabel();
        txtKm = new javax.swing.JTextField();
        lblMapGas2 = new javax.swing.JLabel();
        cbxTipoVehiculo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblName.setText("Fabricante:");

        lblLastName.setText("Modelo:");

        lblPhoneç.setText("Año compra:");

        lblGas.setText("Placa:");

        lblRuc.setText("Capacidad max:");

        lblMapGas.setText("Tipo combustible:");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnInsertVehicle.setText("Guardar");
        btnInsertVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertVehicleActionPerformed(evt);
            }
        });

        lblName1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblName1.setText("Nuevo Vehiculo");

        lblMapGas1.setText("Km:");

        lblMapGas2.setText("Tipo de vehiculo:");

        cbxTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Cisterna", "Volquete", "Maquinaria Pesada" }));
        cbxTipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton2)
                .addGap(60, 60, 60)
                .addComponent(btnInsertVehicle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRuc)
                    .addComponent(lblMapGas)
                    .addComponent(lblMapGas2)
                    .addComponent(lblMapGas1)
                    .addComponent(lblPhoneç)
                    .addComponent(lblName)
                    .addComponent(lblLastName)
                    .addComponent(lblGas))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbxTipoVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtModel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtPurchaseDate)
                        .addComponent(txtCapMax)
                        .addComponent(txtFuel)
                        .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lblName1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblName1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneç))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCapMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRuc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMapGas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMapGas1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMapGas2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnInsertVehicle))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertVehicleActionPerformed
        //validate and capturar datos from gui
        if (!Validator.isNotEmpty(txtManufacturer, txtModel, txtPurchaseDate, txtPlate, txtCapMax, txtFuel, txtKm)) {
            JOptionPane.showMessageDialog(this, "Por favor, complete los campos obligatorios.");
            return;
        }

        if (Validator.isComboSelected(cbxTipoVehiculo)) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione el tipo de vehiculo.");
            return;
        }
        
        if (!Validator.isInteger(txtPurchaseDate.getText())) {
            JOptionPane.showMessageDialog(this, "Año de compra invalido");
            return;
        }
        
         
        
        
        
        
        if (Integer.parseInt(txtPurchaseDate.getText()) < 1990 || Integer.parseInt(txtPurchaseDate.getText()) > 2030) {
            JOptionPane.showMessageDialog(this, "Año de fuera de rango");
            return;
        }
        
        
        if (!Validator.isInteger(txtKm.getText())) {
            JOptionPane.showMessageDialog(this, "Kilometraje invalido");
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(
                this, // Componente padre (tu JFrame o JDialog)
                " Verifique el Km:" + txtKm.getText(), // Mensaje para el usuario
                "Confirmación", // Título de la ventana
                JOptionPane.YES_NO_OPTION, // Tipo de botones (Sí/No)
                JOptionPane.QUESTION_MESSAGE // Icono (Interrogación)
        );

        if (respuesta == JOptionPane.YES_OPTION) {
            
            Vehicle ve = new Vehicle();
            ve.setFuel(txtFuel.getText());
            ve.setModel(txtModel.getText());
            ve.setKm(Integer.parseInt(txtKm.getText()));
            ve.setManufacturer(txtManufacturer.getText());
            ve.setMax_capacity(Integer.parseInt(txtCapMax.getText()));
            ve.setPlate(txtCapMax.getText());
            ve.setPurchas_date(Integer.parseInt(txtPurchaseDate.getText()));
            Object t = cbxTipoVehiculo.getSelectedItem();

            ve.setType(t.toString());
            //call to controller

            if (controll.registerVehicle(ve)) {
                JOptionPane.showMessageDialog(rootPane, "Vehiculo guardado");
                this.dispose();
            } else { 
                JOptionPane.showMessageDialog(rootPane, "Error");
            }

        } else {
            
        }


    }//GEN-LAST:event_btnInsertVehicleActionPerformed

    private void cbxTipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoVehiculoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RegisVehicle dialog = new RegisVehicle(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertVehicle;
    private javax.swing.JComboBox<String> cbxTipoVehiculo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblGas;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMapGas;
    private javax.swing.JLabel lblMapGas1;
    private javax.swing.JLabel lblMapGas2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblPhoneç;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JTextField txtCapMax;
    private javax.swing.JTextField txtFuel;
    private javax.swing.JTextField txtKm;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPlate;
    private javax.swing.JTextField txtPurchaseDate;
    // End of variables declaration//GEN-END:variables
}
