/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.forms.dialogs.register;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import controllers.OperatorController;
import modelo.domain.Operator;
import modelo.util.Validator;
import org.kordamp.ikonli.bootstrapicons.BootstrapIcons;
import org.kordamp.ikonli.boxicons.BoxiconsRegular;
import org.kordamp.ikonli.carbonicons.CarbonIcons;
import org.kordamp.ikonli.dashicons.Dashicons;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author drola
 */
public class RegisOperator extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisOperator.class.getName());

    OperatorController controll = new OperatorController();

    /**
     * Creates new form RegisOperator
     */
    public RegisOperator(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        FontIcon iconPerson = FontIcon.of(BootstrapIcons.FILE_PERSON);
        iconPerson.setIconSize(25);
        lblName.setIcon(iconPerson);

        FontIcon iconDni = FontIcon.of(CarbonIcons.DOC);
        iconDni.setIconSize(25);
        lblDni.setIcon(iconDni);

        FontIcon iconBirthday = FontIcon.of(FontAwesomeSolid.BIRTHDAY_CAKE);
        iconBirthday.setIconSize(25);
        lblFechaIngreso.setIcon(iconBirthday);

        FontIcon iconMap = FontIcon.of(BoxiconsRegular.MAP);
        iconMap.setIconSize(20);
        lblMapGas.setIcon(iconMap);

        FontIcon iconPhone = FontIcon.of(BootstrapIcons.TELEPHONE);
        iconPhone.setIconSize(20);
        lblPhone.setIcon(iconPhone);

        FontIcon iconRuc = FontIcon.of(Dashicons.MEDIA_DOCUMENT);
        iconRuc.setIconSize(20);
        lblBirthday.setIcon(iconRuc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        lblFechaIngreso = new javax.swing.JLabel();
        txtEntryDate = new javax.swing.JTextField();
        txtBirthday = new javax.swing.JTextField();
        lblBirthday = new javax.swing.JLabel();
        lblMapGas = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnInsertCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblName1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblName1.setText("Nuevo Operador");

        lblName.setText("Nombres:");

        lblDni.setText("Dni");

        lblPhone.setText("Contacto:");

        lblFechaIngreso.setText("Fecha Ingreso:");

        lblBirthday.setText("Cumpleaños:");

        lblMapGas.setText("Categoria:");

        txtCategory.setText("Cisterna");
        txtCategory.setEnabled(false);

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnInsertCustomer.setText("Guardar");
        btnInsertCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFechaIngreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEntryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPhone)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDni)
                            .addComponent(lblBirthday)
                            .addComponent(lblMapGas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDni, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(txtBirthday)
                            .addComponent(txtCategory))))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(btnInsertCustomer)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblName1)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaIngreso)
                    .addComponent(txtEntryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBirthday)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMapGas)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnInsertCustomer))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertCustomerActionPerformed
        // working Validator.class

        if (!Validator.isNotEmpty(txtBirthday, txtCategory, txtDni, txtEntryDate, txtName, txtPhoneNumber)) {
            JOptionPane.showMessageDialog(this, "Por favor, complete los campos obligatorios.");
            return;
        }

        if (!Validator.isValidDNI(txtDni.getText())) {
            JOptionPane.showMessageDialog(this, "El DNI debe tener exactamente 8 dígitos numéricos.");
            return;
        }

        if (!Validator.isValidPhone(txtPhoneNumber.getText())) {
            JOptionPane.showMessageDialog(this, "El  Nro celular debe tener exactamente 9 dígitos numéricos.");
            return;
        }

        LocalDate birthDate = Validator.parseDatePeru(txtBirthday.getText());
        LocalDate entryDate = Validator.parseDatePeru(txtEntryDate.getText());

        if (birthDate == null || entryDate == null) {
            JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Use: DD/MM/AAAA (ej: 15/02/1990)");
            return;
        }

        Operator op = new Operator();
        op.setBirthday(birthDate);
        op.setDni(txtDni.getText());
        op.setFullname(txtName.getText());
        op.setEntryDate(entryDate);
        op.setPhonenumber(txtPhoneNumber.getText());
        op.setCategory(txtCategory.getText());

        //call to controller
        if (controll.registerCustomer(op)) {
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }

    }//GEN-LAST:event_btnInsertCustomerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RegisOperator dialog = new RegisOperator(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertCustomer;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblFechaIngreso;
    private javax.swing.JLabel lblMapGas;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEntryDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
