/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.forms.dialogs.register;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import controllers.CategoryMController;
import controllers.ExpenseController;
import controllers.IncomeController;
import controllers.OperatorController;
import java.sql.SQLException;
import modelo.domain.Customer;
import modelo.domain.Flete;
import modelo.domain.transaction.CategoryM;
import modelo.domain.transaction.Expense;
import modelo.domain.transaction.Income;
import modelo.domain.transaction.IncomeCreator;
import modelo.domain.transaction.Transaction;
import modelo.domain.transaction.TransactionCreator;


/**
 *
 * @author drola
 */
public class RegisIncomeFlete extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisIncomeFlete.class.getName());
    //controllers
    private CategoryMController controllCat = new CategoryMController();
    private  IncomeController controllInco = new IncomeController();
    private TransactionCreator creator = new IncomeCreator();
    private Flete fleteCurrent = null;
    private CategoryM categoryMSelectedGlob = null;

    /**
     * Creates new form RegisOperator
     */
    public RegisIncomeFlete(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public RegisIncomeFlete(Flete flete) {
        this(new javax.swing.JFrame(), true);
        this.fleteCurrent = flete;
        injectCategoriesToCbx();
        injectFleteCurrent();

    }

    //my methods
    private void injectFleteCurrent() {
        lblFleteDoc.setText(fleteCurrent.getNumDoc());
    }

    private void injectCategoriesToCbx() {
        try {
            List<CategoryM> list = controllCat.listIncomes();
             // Limpiamos el combo por si acaso
        cbxCategories.removeAllItems();

        // Agregamos una opción inicial
        CategoryM placeholder = new CategoryM();
        placeholder.setId(-1);
        placeholder.setName("--- Seleccione un categoria");

        cbxCategories.addItem(placeholder);

        for (CategoryM c : list) {
            cbxCategories.addItem(c);
        }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error:" +e.getMessage());
        }
        

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName1 = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        txtImport = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnInsertExpenseFleteC = new javax.swing.JButton();
        lblName2 = new javax.swing.JLabel();
        lblFleteDoc = new javax.swing.JLabel();
        cbxCategories = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblName1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblName1.setText("Nuevo Ingreso");

        lblCategory.setText("Tipo:");

        lblAmount.setText("Importe:");

        txtImport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImportKeyTyped(evt);
            }
        });

        lblDescription.setText("Descripcion:");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnInsertExpenseFleteC.setBackground(new java.awt.Color(102, 153, 255));
        btnInsertExpenseFleteC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInsertExpenseFleteC.setText("Guardar");
        btnInsertExpenseFleteC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertExpenseFleteCActionPerformed(evt);
            }
        });

        lblName2.setText("Flete :");

        lblFleteDoc.setText("F-012426");

        cbxCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton2)
                        .addGap(40, 40, 40)
                        .addComponent(btnInsertExpenseFleteC))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName2)
                                    .addComponent(lblCategory)
                                    .addComponent(lblAmount))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDescription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtImport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblFleteDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxCategories, 0, 178, Short.MAX_VALUE))
                            .addComponent(lblName1))))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblName1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFleteDoc)
                    .addComponent(lblName2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategory))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescription))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnInsertExpenseFleteC))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertExpenseFleteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertExpenseFleteCActionPerformed
        // 1. PRIMERA ADUANA: Validación de flete actual (Protección contra nulos)
        if (fleteCurrent == null) {
            JOptionPane.showMessageDialog(this, "Error interno: No hay un flete activo seleccionado.", "Error Crítico", JOptionPane.ERROR_MESSAGE);
            return;
        }

// 2. SEGUNDA ADUANA: Validación del ComboBox (Protección contra el Placeholder)
        Object selection = cbxCategories.getSelectedItem();

// Validamos que sea un objeto CategoryM
        if (!(selection instanceof CategoryM)) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una categoría válida para el gasto.", "Validación", JOptionPane.WARNING_MESSAGE);
            cbxCategories.requestFocus();
            return;
        }

        CategoryM categoriaSeleccionada = (CategoryM) selection;

// Validamos que no sea el "Placeholder" tramposo (--- Seleccione un cliente ---)
        if (categoriaSeleccionada.getId() == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una categoría real de la lista desplegable.", "Selección Inválida", JOptionPane.WARNING_MESSAGE);
            cbxCategories.requestFocus();
            return;
        }

// 3. TERCERA ADUANA: Validación de la Descripción
        String descText = txtDescription.getText().trim();
        if (descText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La descripción no puede estar vacía.", "Validación", JOptionPane.WARNING_MESSAGE);
            txtDescription.requestFocus();
            return;
        }

// 4. CUARTA ADUANA: Validación del Importe (Vacíos, Letras y Negativos)
        String importText = txtImport.getText().trim();
        if (importText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El importe no puede estar vacío.", "Validación", JOptionPane.WARNING_MESSAGE);
            txtImport.requestFocus();
            return;
        }

        double amountParsed = 0.0;
        try {
            amountParsed = Double.parseDouble(importText);

            // Regla de negocio: Un gasto no puede ser cero o negativo
            if (amountParsed <= 0) {
                JOptionPane.showMessageDialog(this, "El importe debe ser mayor a S/ 0.00", "Validación", JOptionPane.WARNING_MESSAGE);
                txtImport.selectAll(); // Sombreado automático para corregir rápido
                txtImport.requestFocus();
                return;
            }
        } catch (NumberFormatException ex) {
            // Atrapa letras, comas o símbolos extraños
            JOptionPane.showMessageDialog(this, "El importe debe ser un número válido (ej. 150.50).", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtImport.selectAll();
            txtImport.requestFocus();
            return;
        }
        
        
// 5. EJECUCIÓN: Todo perfecto, construimos el objeto y guardamos en BD
        Income e = (Income)creator.prepararTransaccion(amountParsed, descText, categoriaSeleccionada);
         e.setIdLoad(0);         // 0 porque no esta asociado a ningun fete
//        e.setCategory(categoriaSeleccionada);
//        e.setDescription(descText);
//        e.setAmount(amountParsed);
       


        boolean b = controllInco.insertIncome(e);


        if (b) {
            JOptionPane.showMessageDialog(this, "Ingreso guardado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); // SOLO cerramos si la BD lo aceptó
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar en la Base de Datos. Por favor intenta de nuevo.", "Error SQL", JOptionPane.ERROR_MESSAGE);
           
        }

    }//GEN-LAST:event_btnInsertExpenseFleteCActionPerformed

    private void cbxCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriesActionPerformed

    }//GEN-LAST:event_cbxCategoriesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtImportKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImportKeyTyped
        char c = evt.getKeyChar();
        // Si no es un número y no es un punto decimal...
        if (!Character.isDigit(c) && c != '.') {
            evt.consume(); // ... "consume" la tecla, es decir, ignora lo que el usuario apretó.
        }

        // Evitar que pongan dos puntos decimales (ej: "22..5")
        if (c == '.' && txtImport.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtImportKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RegisIncomeFlete dialog = new RegisIncomeFlete(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertExpenseFleteC;
    private javax.swing.JComboBox<CategoryM> cbxCategories;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblFleteDoc;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtImport;
    // End of variables declaration//GEN-END:variables
}
