/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.forms.minDialogs;

import javax.swing.JOptionPane;
import controllers.IncomeController;
import controllers.LoadController;
import modelo.domain.Load;
import modelo.domain.transaction.CategoryM;
import modelo.domain.transaction.Income;
import modelo.dto.LoadDTO;
import modelo.util.IconManager;
import org.kordamp.ikonli.boxicons.BoxiconsLogos;
import org.kordamp.ikonli.boxicons.BoxiconsRegular;
import org.kordamp.ikonli.carbonicons.CarbonIcons;
import vista.forms.dialogs.edit.AddAbono;
import vista.forms.dialogs.edit.EditLoad;

/**
 *
 * @author drola
 */
public class OptionsLoad extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OptionsLoad.class.getName());
    private LoadDTO cargaData;
    private LoadController controllLoad = new LoadController();
    private IncomeController controllInco= new IncomeController();
    /**
     * Creates new form OptionsLoad
     */
    public OptionsLoad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public OptionsLoad(LoadDTO l) {
        this(new javax.swing.JFrame(), true);
        this.cargaData = l;
        
        if(cargaData.getPaymentStatus().equalsIgnoreCase("pagado")){
            btnAddAbono.setEnabled(false);
        }
        
        loadIncos();
    }
    private void loadIncos (){
        IconManager.setIkonliIcon(btnAddAbono, BoxiconsRegular.MONEY, 25);
         IconManager.setIkonliIcon(btnEdit, CarbonIcons.WORKSPACE, 25);
          IconManager.setIkonliIcon(btnDelete,CarbonIcons.DELETE , 25);
          IconManager.setIkonliIcon(btnBack, BoxiconsRegular.ARROW_BACK, 25);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNameCustomer = new javax.swing.JLabel();
        btnAddAbono = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblNameCustomer.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNameCustomer.setText("Gestion de Carga");

        btnAddAbono.setBackground(new java.awt.Color(102, 153, 255));
        btnAddAbono.setText("Registrar abonos");
        btnAddAbono.addActionListener(this::btnAddAbonoActionPerformed);

        btnEdit.setText("Editar Volumen /precio");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setText("Eliminar carga");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setBorder(null);
        btnBack.setMaximumSize(new java.awt.Dimension(32, 32));
        btnBack.setMinimumSize(new java.awt.Dimension(32, 32));
        btnBack.setPreferredSize(new java.awt.Dimension(32, 32));
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNameCustomer)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete)
                            .addComponent(btnEdit)
                            .addComponent(btnAddAbono))
                        .addGap(72, 72, 72))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblNameCustomer)
                .addGap(53, 53, 53)
                .addComponent(btnAddAbono)
                .addGap(31, 31, 31)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        EditLoad w = new EditLoad(cargaData);
        w.setLocationRelativeTo(this); // Centrar
        w.setResizable(false);        // No redimensionar
        this.dispose();
        w.setVisible(true);            //mostrar

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que deseas eliminar esta carga?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

// 2. Tomamos la decisión basada en la variable
        if (respuesta == JOptionPane.YES_OPTION) {
            // AQUÍ pones tu código para eliminar (llamar al controlador)
            Load l = new Load();
            l.setId(cargaData.getIdLoad());
            controllLoad.delete(l);
            this.dispose();
        } else {
            // El usuario cerró la ventana o marcó NO
            System.out.println("Acción cancelada");
            this.dispose();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAbonoActionPerformed
        
       AddAbono w = new AddAbono(cargaData);
       w.setLocationRelativeTo(this); // Centrar
        w.setResizable(false);        // No redimensionar
        this.dispose();
        w.setVisible(true);    
    }//GEN-LAST:event_btnAddAbonoActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                OptionsLoad dialog = new OptionsLoad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAbono;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNameCustomer;
    // End of variables declaration//GEN-END:variables
}
