/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.forms.minDialogs;

import controllers.VehicleController;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.domain.Vehicle;
import modelo.util.Validator;

/**
 *
 * @author drola
 */
public class UpdateKm extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateKm.class.getName());
    private Vehicle vehicle = null;
    private VehicleController controlVe = new VehicleController();

    /**
     * Creates new form UpdateKm
     */
    public UpdateKm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

 
    public UpdateKm(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    
    public UpdateKm(java.awt.Dialog parent, Vehicle vehicle) {
        this(parent, true); // Llama al constructor #2
        this.vehicle = vehicle;
        injectData();
    }

    private void injectData() {
        lblNamevehicle.setText("Vehiculo: "+vehicle.getManufacturer() + " " + vehicle.getModel());
        lblKmCurrent.setText("Kilometraje actual: "+String.valueOf(vehicle.getKm()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNamevehicle = new javax.swing.JLabel();
        lblKmCurrent = new javax.swing.JLabel();
        lblKmNew = new javax.swing.JLabel();
        btnSAve = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtKmNew = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Actualizar");

        lblNamevehicle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblNamevehicle.setText("Vehiculo:");

        lblKmCurrent.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblKmCurrent.setText("Kilometraje actual:");

        lblKmNew.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblKmNew.setText("Kilometraje Nuevo:");

        btnSAve.setBackground(new java.awt.Color(102, 153, 255));
        btnSAve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSAve.setText("Guardar");
        btnSAve.addActionListener(this::btnSAveActionPerformed);

        btnback.setText("Cancelar");
        btnback.addActionListener(this::btnbackActionPerformed);

        jLabel5.setText("**Confirme el kilometraje final antes de continuar.");

        txtKmNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKmNewKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamevehicle)
                            .addComponent(lblKmCurrent)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblKmNew)
                                .addGap(18, 18, 18)
                                .addComponent(txtKmNew, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnback)
                        .addGap(55, 55, 55)
                        .addComponent(btnSAve)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(lblNamevehicle)
                .addGap(18, 18, 18)
                .addComponent(lblKmCurrent)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKmNew)
                    .addComponent(txtKmNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(btnSAve))
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnSAveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAveActionPerformed
        if (!Validator.isInteger(txtKmNew.getText())) {
            JOptionPane.showMessageDialog(this, "Kilometraje invalido, no use decimales");
            return;
        }
        int kmNew = Integer.parseInt(txtKmNew.getText());
        vehicle.setKm(kmNew);

        try {

            if (controlVe.updateKm(vehicle)) {
                JOptionPane.showMessageDialog(this, "Viaje finalizado correctamente.");
                this.dispose();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSAveActionPerformed

    private void txtKmNewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKmNewKeyTyped
        char c = evt.getKeyChar();

        // Solo permite números (0-9). 
        // Los caracteres de control como backspace o enter suelen pasar por defecto,
        // pero aquí los protegemos explícitamente.
        if (!(Character.isDigit(c) || (c == java.awt.event.KeyEvent.VK_BACK_SPACE) || (c == java.awt.event.KeyEvent.VK_DELETE))) {
            getToolkit().beep(); // Hace un sonido de advertencia (opcional)
            evt.consume();
        }
    }//GEN-LAST:event_txtKmNewKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                UpdateKm dialog = new UpdateKm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSAve;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKmCurrent;
    private javax.swing.JLabel lblKmNew;
    private javax.swing.JLabel lblNamevehicle;
    private javax.swing.JTextField txtKmNew;
    // End of variables declaration//GEN-END:variables
}
