/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.forms;

import controllers.UserController;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.domain.User;
import modelo.util.ConfigManager;
import modelo.util.IconManager;
import modelo.util.conexion.ConexionBD;

import net.coobird.thumbnailator.Thumbnails;
import org.kordamp.ikonli.boxicons.BoxiconsSolid;
import org.kordamp.ikonli.carbonicons.CarbonIcons;

/**
 *
 * @author drola
 */
public class Loginform extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Loginform.class.getName());

    /**
     * Creates new form test
     */
    public Loginform() {
        initComponents();
        loadIconsAndParams();
        btnsConfig();
        verificarConexionAlIniciar();

    }

    private void verificarConexionAlIniciar() {
        // 1. Estado inicial: Deshabilitamos el botón para evitar errores
        btnLogin.setEnabled(false);
        lblStatusDB.setText("Verificando servicios de Neon...");
        lblStatusDB.setForeground(Color.GRAY);

        // 2. Ejecutamos la prueba en un hilo para no congelar el Login
        new Thread(() -> {
            // Usamos el método que ya mejoramos en tu clase ConexionBD
            String status = ConexionBD.getServerInfo();

            // 3. Regresamos a la interfaz para mostrar el resultado
            java.awt.EventQueue.invokeLater(() -> {
                lblStatusDB.setText(status);

                if (status.contains("Conectado")) {
                    lblStatusDB.setForeground(new Color(40, 180, 99)); // Verde
                    btnLogin.setEnabled(true); // ¡Todo listo!
                } else {
                    lblStatusDB.setForeground(new Color(192, 57, 43)); // Rojo
                    btnLogin.setEnabled(true); // Dejamos que intente por si acaso
                    btnLogin.setText("Reintentar");
                }
            });
        }).start();
    }

    public final void loadIconsAndParams() {
        
        this.setLocationRelativeTo(this); // Centrar
        //this.setResizable(false);        // No redimensionar

        //inject logo enterprise 
        try {
            java.net.URL resource = getClass().getResource("/logos/logoPrincipal.png");

            if (resource == null) {
                System.err.println("ERROR: El archivo no existe en la ruta especificada.");
                return;
            }

            BufferedImage logoRedimensionado = Thumbnails.of(resource)
                    .size(190, 265)
                    .keepAspectRatio(true)
                    .asBufferedImage();

            lblLogo.setIcon(new ImageIcon(logoRedimensionado));
            lblLogo.setText(""); // Quita el texto "jLabel1" si existe
        } catch (IOException e) {
            e.printStackTrace();
        }
        IconManager.setIkonliIcon(lblUser, BoxiconsSolid.USER_DETAIL, 20);
        IconManager.setIkonliIcon(lblpassword, CarbonIcons.PASSWORD, 20);

        //params for dev
        lblBuildNumber.setText(ConfigManager.getVersionAndBuildNumber());
        System.err.println(ConfigManager.getVersionAndBuildNumber());
    }

    public final void btnsConfig() {
        // Estilo para un botón Pro
        // btnBack.setBackground(new Color(230, 230, 230)); // El azul mencionado
        //btnBack.setForeground(new Color(60, 60, 60)); // Texto blanco para que resalte
        btnBack.putClientProperty("JButton.buttonType", "roundRect"); // Bordes redondeados modernos
        btnBack.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Que cambie la mano al pasar el mouse
        // Estilo para un botón Pro
        btnLogin.setBackground(new Color(33, 150, 243)); // El azul mencionado
        btnLogin.setForeground(Color.WHITE); // Texto blanco para que resalte
        btnLogin.putClientProperty("JButton.buttonType", "roundRect"); // Bordes redondeados modernos
        btnLogin.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Que cambie la mano al pasar el mouse
        btnLogin.putClientProperty("JButton.focusedBackground", new Color(25, 118, 210));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblBuildNumber = new javax.swing.JLabel();
        txtJpassword = new javax.swing.JPasswordField();
        lblStatusDB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar sesion");

        bg.setBackground(new java.awt.Color(204, 204, 204));
        bg.setPreferredSize(new java.awt.Dimension(360, 540));

        lblUser.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(102, 102, 102));

        txtUser.setBackground(new java.awt.Color(215, 215, 215));
        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUser.setBorder(null);
        txtUser.addActionListener(this::txtUserTextoUsuarioActionPerformed);

        lblpassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(102, 102, 102));

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setText("Salir");
        btnBack.setPreferredSize(new java.awt.Dimension(27, 21));
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnLogin.setBackground(new java.awt.Color(242, 242, 242));
        btnLogin.setText("Acceder");
        btnLogin.setPreferredSize(new java.awt.Dimension(40, 21));
        btnLogin.addActionListener(this::btnLoginBotonLoginActionPerformed);

        lblBuildNumber.setBackground(new java.awt.Color(204, 204, 204));
        lblBuildNumber.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lblBuildNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblBuildNumber.setText("Version: v0.1.0-BETA | Build: 20260221-1706");

        txtJpassword.setBackground(new java.awt.Color(215, 215, 215));
        txtJpassword.setBorder(null);
        txtJpassword.setPreferredSize(new java.awt.Dimension(64, 20));
        txtJpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJpasswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJpasswordKeyTyped(evt);
            }
        });

        lblStatusDB.setText("status conection");
        lblStatusDB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblStatusDB.setMaximumSize(new java.awt.Dimension(178, 16));
        lblStatusDB.setMinimumSize(new java.awt.Dimension(178, 16));
        lblStatusDB.setPreferredSize(new java.awt.Dimension(178, 16));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBuildNumber)
                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtJpassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUser, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(bgLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblStatusDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(bgLayout.createSequentialGroup()
                                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(11, 11, 11))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblStatusDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblBuildNumber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginBotonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginBotonLoginActionPerformed

        if (btnLogin.getText().equals("Reintentar")) {
            // Si falló antes, este botón ahora sirve para volver a chequear
            btnLogin.setText("Ingresar");
            verificarConexionAlIniciar();
        } else {
            // Aquí va tu lógica normal de login (validar usuario y clave)
            // ejecutarLogin(); // Tu lógica de validar usuario en la BD
            String username = txtUser.getText().trim();
            String password = new String(txtJpassword.getPassword()); // Recuerda lo que hablamos del JPasswordField

            if (username.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, completa ambos campos.");
                return;
            }

            // Instanciamos el controlador
            UserController userControl = new UserController();
            User usuarioLogueado = userControl.validateLogin(username, password);

            if (usuarioLogueado != null) {
                JOptionPane.showMessageDialog(this, "¡Bienvenido " + usuarioLogueado.getFullName() + "!");

                // Pasamos el usuario a la ventana principal
                InicialForm principal = new InicialForm(usuarioLogueado);
                principal.setVisible(true);
                this.dispose(); // Cierra el login
            } else {
                JOptionPane.showMessageDialog(this, "Credenciales incorrectas o usuario inactivo.", "Error", JOptionPane.ERROR_MESSAGE);
                txtJpassword.setText(""); // Limpiamos la clave
                txtJpassword.requestFocus();
            }
        }


    }//GEN-LAST:event_btnLoginBotonLoginActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtUserTextoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserTextoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserTextoUsuarioActionPerformed

    private void txtJpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJpasswordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJpasswordKeyTyped

    private void txtJpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJpasswordKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnLogin.doClick();
        }
    }//GEN-LAST:event_txtJpasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Loginform().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblBuildNumber;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblStatusDB;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JPasswordField txtJpassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
