/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.forms.dialogs.edit;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import controllers.IncomeController;
import controllers.LoadController;
import modelo.domain.transaction.CategoryM;
import modelo.domain.transaction.Income;
import modelo.dto.LoadDTO;

/**
 *
 * @author drola
 */
public class AddAbono extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddAbono.class.getName());
    private LoadDTO cargaData;
    private IncomeController controllIncome = new IncomeController();

    /**
     * Creates new form AddAbono
     */
    public AddAbono(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public AddAbono(LoadDTO l) {
        this(new javax.swing.JFrame(), true);
        this.cargaData = l;
        injectData();
    }

    private void injectData() {
        lblNameCustomer.setText(cargaData.getNameCustomer());
        lblAmountFlete.setText(cargaData.getAmount() > 0 ? "S/ " + String.format("%.2f", cargaData.getAmount()) : "Sin asingnar");
        lblBalance.setText(cargaData.getImportBalance() > 0 ? "S/ " + String.format("%.2f", cargaData.getImportBalance()) : "Sin asignar");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblName1 = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        lblNameCustomer = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblDni = new javax.swing.JLabel();
        txtImport = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblName4 = new javax.swing.JLabel();
        lblAmountFlete = new javax.swing.JLabel();
        lblName5 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblName1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblName1.setText("Nuevo Abono");

        lblName3.setText("Cliente:");

        lblNameCustomer.setText("Nombre Cliente");

        lblPhone.setText("Descripcion:");

        lblDni.setText("Importe:");

        txtImport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImportKeyTyped(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        btnSave.setBackground(java.awt.SystemColor.activeCaption);
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setText("Guardar");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        lblName4.setText("Precio flete:");

        lblAmountFlete.setText("-----------");

        lblName5.setText("Deuda actual:");

        lblBalance.setText("-----------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lblName1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblName3)
                        .addGap(42, 42, 42)
                        .addComponent(lblNameCustomer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhone)
                            .addComponent(lblDni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtImport, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton2)
                        .addGap(80, 80, 80)
                        .addComponent(btnSave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName4)
                            .addComponent(lblName5))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBalance)
                            .addComponent(lblAmountFlete))))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblName1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName3)
                    .addComponent(lblNameCustomer))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName4)
                    .addComponent(lblAmountFlete))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName5)
                    .addComponent(lblBalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhone)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(txtImport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnSave))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // ADUANA 0: Protección contra nulos (Para que cargaData.getAmount() no explote)
        if (cargaData == null) {
            JOptionPane.showMessageDialog(this, "Error interno: No hay datos de carga seleccionados.", "Error Crítico", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (txtDescription.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La descripción no puede estar vacía", "Validación", JOptionPane.WARNING_MESSAGE);
            txtDescription.requestFocus();
            return;
        }

        if (txtImport.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo Importe está vacío", "Validación", JOptionPane.WARNING_MESSAGE);
            txtImport.requestFocus();
            return;
        }

        double addAbono;
        try {
            addAbono = Double.parseDouble(txtImport.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido en Importe (ej. 150.50)", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtImport.selectAll(); // <-- Toque Pro de UX
            txtImport.requestFocus();
            return;
        }

        if (addAbono <= 0) {
            JOptionPane.showMessageDialog(this, "El importe debe ser mayor a 0", "Validación", JOptionPane.WARNING_MESSAGE);
            txtImport.selectAll(); // <-- Toque Pro de UX
            txtImport.requestFocus();
            return;
        }

// Lógica de Cobranza Dinámica
        double newImporte = Double.parseDouble(txtImport.getText());
        double balance = cargaData.getImportBalance();

        if (addAbono > balance) {
            JOptionPane.showMessageDialog(this,
                    "Error: El abono (S/ " + newImporte + ") supera el saldo deudor actual (S/ " + balance + ").\nPor favor, corrige el monto.", "Monto Excedido", JOptionPane.WARNING_MESSAGE);
            txtImport.selectAll(); // <-- Toque Pro de UX
            txtImport.requestFocus();
            return;
        }

// EJECUCIÓN 
        Income i = new Income();
        i.setIdLoad(cargaData.getIdLoad());

        CategoryM c = new CategoryM();
        c.setId(1); // INGRESO FLETE
        i.setCategory(c);

        i.setDescription(txtDescription.getText().trim());
        i.setAmount(addAbono);
        i.setDate(LocalDate.now());

        boolean inserted = controllIncome.insertIncome(i);

        if (inserted) {
            JOptionPane.showMessageDialog(this, "Abono guardado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos", "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtImportKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImportKeyTyped
        char c = evt.getKeyChar();
        // Si no es un número y no es un punto decimal...
        if (!Character.isDigit(c) && c != '.') {
            evt.consume(); // ... "consume" la tecla, es decir, ignora lo que el usuario apretó.
        }

        // Evitar que pongan dos puntos decimales (ej: "22..5")
        if (c == '.' && txtImport.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtImportKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddAbono dialog = new AddAbono(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAmountFlete;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblNameCustomer;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtImport;
    // End of variables declaration//GEN-END:variables
}
