/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.forms.dialogs.edit;

import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import controllers.ExpenseController;
import controllers.IncomeController;
import controllers.LoadController;
import modelo.domain.Flete;
import modelo.domain.transaction.CategoryM;
import modelo.domain.transaction.Expense;
import modelo.domain.transaction.Income;
import modelo.dto.DebtDTO;
import modelo.dto.FinanceOperatorDTO;
import modelo.dto.LoadDTO;
import vista.forms.InicialForm;

/**
 *
 * @author drola
 */
public class EditRowOperatorManager extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditRowOperatorManager.class.getName());
    private FinanceOperatorDTO financeOperatorDTO;
    private InicialForm inicialForm;
    private ExpenseController controllExpe = new ExpenseController();

    /**
     * Creates new form AddAbono
     */
    public EditRowOperatorManager(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public EditRowOperatorManager(FinanceOperatorDTO financeOperatorDTO, InicialForm inicialForm) {
        this(inicialForm, true);
        this.financeOperatorDTO = financeOperatorDTO;
        this.inicialForm = inicialForm;
        injectData();

    }

    private void injectData() {
        lblTotalImporte.setText(String.valueOf(financeOperatorDTO.getAmount()));
        txtDescription.setText(financeOperatorDTO.getDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblabono = new javax.swing.JLabel();
        txtImport = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnInsertExpenseFleteC = new javax.swing.JButton();
        lblNameCustomerTitle = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        lblTotalImporte = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblabono.setText("Nuevo Importe:");

        txtImport.setBackground(new java.awt.Color(255, 153, 153));
        txtImport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImportKeyTyped(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        btnInsertExpenseFleteC.setText("Guardar");
        btnInsertExpenseFleteC.addActionListener(this::btnInsertExpenseFleteCActionPerformed);

        lblNameCustomerTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNameCustomerTitle.setText("Editar Registro");

        lblName3.setText("Importe Actual:");

        lblTotalImporte.setText("99999");

        lblPhone.setText("Descripcion:");

        txtDescription.setText("Abono parcial");
        txtDescription.addActionListener(this::txtDescriptionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName3)
                            .addComponent(lblPhone)
                            .addComponent(lblabono))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(lblTotalImporte)
                            .addComponent(txtImport)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton2)
                        .addGap(59, 59, 59)
                        .addComponent(btnInsertExpenseFleteC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblNameCustomerTitle)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblNameCustomerTitle)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName3)
                    .addComponent(lblTotalImporte))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblabono)
                    .addComponent(txtImport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnInsertExpenseFleteC))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertExpenseFleteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertExpenseFleteCActionPerformed



        FinanceOperatorDTO i = new FinanceOperatorDTO();
            i.setId(financeOperatorDTO.getId());
            i.setOperator(financeOperatorDTO.getOperator());
            i.setIdFlete(financeOperatorDTO.getIdFlete());
            CategoryM c = new CategoryM();                  //crear formulario  para que el user seleccione la categoria
            c.setId(7); // 1 because its sueldo/comisiones
            i.setCategory(c);
            i.setDescription(txtDescription.getText());
            i.setAmount(Double.parseDouble(txtImport.getText()));
            i.setDate(LocalDate.now());
            //insert to DB
            boolean b = controllExpe.updateWithOperator(i);
            if (b) {
                JOptionPane.showMessageDialog(this, "Abono guardado con exito");


                this.dispose();
            }



    }//GEN-LAST:event_btnInsertExpenseFleteCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtImportKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImportKeyTyped
        char c = evt.getKeyChar();
    // Si no es un número y no es un punto decimal...
    if (!Character.isDigit(c) && c != '.') {
        evt.consume(); // ... "consume" la tecla, es decir, ignora lo que el usuario apretó.
    }
    
    // Evitar que pongan dos puntos decimales (ej: "22..5")
    if (c == '.' && txtImport.getText().contains(".")) {
        evt.consume();
    }
    }//GEN-LAST:event_txtImportKeyTyped

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EditRowOperatorManager dialog = new EditRowOperatorManager(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertExpenseFleteC;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblNameCustomerTitle;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblTotalImporte;
    private javax.swing.JLabel lblabono;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtImport;
    // End of variables declaration//GEN-END:variables
}
