/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.forms.dialogs.edit;

import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import controllers.IncomeController;
import controllers.LoadController;
import modelo.domain.Flete;
import modelo.domain.transaction.CategoryM;
import modelo.domain.transaction.Income;
import modelo.dto.DebtDTO;
import modelo.dto.LoadDTO;
import vista.forms.InicialForm;

/**
 *
 * @author drola
 */
public class EditRowDebtors extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditRowDebtors.class.getName());
    private DebtDTO debtDTO;
    private InicialForm inicialForm;
    private Flete fleteCurrent = null;
    private IncomeController controllIncome = new IncomeController();

    /**
     * Creates new form AddAbono
     */
    public EditRowDebtors(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public EditRowDebtors(DebtDTO d, InicialForm inicialForm, Flete fleteCurrent) {
        this(inicialForm, true);
        this.debtDTO = d;
        this.inicialForm = inicialForm;
        this.fleteCurrent = fleteCurrent;
        injectData();

    }

    private void injectData() {
        lblNameCustomerTitle.setText("Cliente: " + debtDTO.getNameCustomer());
        lblTotalAbono.setText(String.valueOf(debtDTO.getAbono()));
        lblPriceFlete.setText(String.valueOf(debtDTO.getPriceFlete()));
        lblBalance.setText(String.valueOf(debtDTO.getBalance()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNameCustomerTitle = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        lblPriceFlete = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        lblTotalAbono = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblabono = new javax.swing.JLabel();
        txtImport = new javax.swing.JTextField();
        btnInsertExpenseFleteC = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblNameCustomerTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNameCustomerTitle.setText("Cliente:          ");

        lblName2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName2.setText("Precio flete:");

        lblPriceFlete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPriceFlete.setText("99999");

        lblName3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName3.setText("Total abonos:");

        lblTotalAbono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalAbono.setText("99999");

        lblName4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName4.setText("Por pagar");

        lblBalance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBalance.setText("99999");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhone.setText("Descripcion:");

        txtDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescription.setText("Abono parcial");

        lblabono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblabono.setText("Importe:");

        txtImport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtImport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImportKeyTyped(evt);
            }
        });

        btnInsertExpenseFleteC.setBackground(java.awt.SystemColor.activeCaption);
        btnInsertExpenseFleteC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInsertExpenseFleteC.setText("Guardar");
        btnInsertExpenseFleteC.addActionListener(this::btnInsertExpenseFleteCActionPerformed);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Registrar Abono");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(79, 79, 79)
                .addComponent(btnInsertExpenseFleteC)
                .addGap(134, 134, 134))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblName3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                    .addComponent(lblTotalAbono))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblName2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPriceFlete)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName4)
                                    .addComponent(lblPhone)
                                    .addComponent(lblabono))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBalance)
                                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtImport, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblNameCustomerTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(lblNameCustomerTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName2)
                    .addComponent(lblPriceFlete))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName3)
                    .addComponent(lblTotalAbono))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName4)
                    .addComponent(lblBalance))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblabono)
                    .addComponent(txtImport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertExpenseFleteC)
                    .addComponent(jButton2))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertExpenseFleteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertExpenseFleteCActionPerformed
        // 1. ADUANA 1: Validar que el objeto global de la deuda exista
        if (debtDTO == null) {
            JOptionPane.showMessageDialog(this, "Error interno: No hay un registro de deuda seleccionado.", "Error Crítico", JOptionPane.ERROR_MESSAGE);
            return; // Abortamos, pero la ventana se queda abierta
        }

// 2. ADUANA 2: Validar que no haya campos de texto vacíos
        String descText = txtDescription.getText().trim();
        if (descText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa una descripción para el abono.", "Validación", JOptionPane.WARNING_MESSAGE);
            txtDescription.requestFocus();
            return;
        }

        String importText = txtImport.getText().trim();
        if (importText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El importe del abono no puede estar vacío.", "Validación", JOptionPane.WARNING_MESSAGE);
            txtImport.requestFocus();
            return;
        }

// 3. ADUANA 3: Parseo Seguro y Lógica de Negocio Básica (No negativos)
        double importeAbono = 0.0;
        try {
            importeAbono = Double.parseDouble(importText);

            // Un abono jamás puede ser cero o un número negativo
            if (importeAbono <= 0) {
                JOptionPane.showMessageDialog(this, "El abono debe ser mayor a S/ 0.00", "Validación", JOptionPane.WARNING_MESSAGE);
                txtImport.selectAll();
                txtImport.requestFocus();
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El importe ingresado no es un número válido (ej. 150.50).", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtImport.selectAll();
            txtImport.requestFocus();
            return;
        }

// 4. ADUANA 4: Lógica de Cobranza (Validar que no pague de más)
        double balance = debtDTO.getBalance();
        if (importeAbono > balance) {
            // Le decimos exactamente de cuánto es el error para que lo corrija
            JOptionPane.showMessageDialog(this, "Error: El abono (S/ " + importeAbono + ") supera el saldo deudor actual (S/ " + balance + ").\nPor favor, corrige el monto.", "Monto Excedido", JOptionPane.WARNING_MESSAGE);
            txtImport.selectAll(); // Seleccionamos el texto para que lo borre rápido
            txtImport.requestFocus();
            return; // ¡MAGIA! No hacemos 'this.dispose()'. El usuario simplemente corrige el número en la misma ventana.
        }

// 5. EJECUCIÓN: Todo está perfecto, procedemos a guardar
        Income i = new Income();
        i.setIdLoad(debtDTO.getIdLoad());

        CategoryM c = new CategoryM();
        c.setId(1); // 1 = INGRESO FLETE
        i.setCategory(c);

        i.setDescription(descText);
        i.setAmount(importeAbono); // Usamos la variable ya validada, no parseamos de nuevo
        i.setDate(LocalDate.now());

// Insertar en BD
        boolean b = controllIncome.insertIncome(i);
        if (b) {
            JOptionPane.showMessageDialog(this, "Abono guardado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // (Aquí va tu código comentado para actualizar las tablas cuando lo necesites)
            this.dispose(); // SOLO cerramos la ventana si la base de datos lo guardó bien
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar en la Base de Datos. Revisa tu conexión.", "Error SQL", JOptionPane.ERROR_MESSAGE);
            // Tampoco cerramos aquí por si fue un parpadeo del internet
        }


    }//GEN-LAST:event_btnInsertExpenseFleteCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtImportKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImportKeyTyped
        char c = evt.getKeyChar();
        // Si no es un número y no es un punto decimal...
        if (!Character.isDigit(c) && c != '.') {
            evt.consume(); // ... "consume" la tecla, es decir, ignora lo que el usuario apretó.
        }

        // Evitar que pongan dos puntos decimales (ej: "22..5")
        if (c == '.' && txtImport.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtImportKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EditRowDebtors dialog = new EditRowDebtors(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertExpenseFleteC;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblNameCustomerTitle;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPriceFlete;
    private javax.swing.JLabel lblTotalAbono;
    private javax.swing.JLabel lblabono;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtImport;
    // End of variables declaration//GEN-END:variables
}
