/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.forms.cards;

import java.awt.Color;
import java.awt.Insets;
import java.util.List;

import modelo.domain.Flete;
import modelo.dto.LoadDTO;
import modelo.dto.LoadDetailDTO;
import modelo.util.ConfigManager;
import modelo.util.IconManager;
import org.kordamp.ikonli.bootstrapicons.BootstrapIcons;
import org.kordamp.ikonli.boxicons.BoxiconsRegular;
import org.kordamp.ikonli.carbonicons.CarbonIcons;
import org.kordamp.ikonli.dashicons.Dashicons;
import org.kordamp.ikonli.fontawesome5.FontAwesomeSolid;
import org.kordamp.ikonli.swing.FontIcon;
import vista.forms.InicialForm;


import vista.forms.minDialogs.OptionsLoad;

/**
 *
 * @author drola
 */
public class CardLoad extends javax.swing.JPanel {

    /**
     * Creates new form CardViajes
     */
    private LoadDTO cargaData;
    private InicialForm inicialForm;
    private Flete fleteCurrent;

    public CardLoad(LoadDTO cargaData, InicialForm jf, Flete fleteCurrent) {
        this.cargaData = cargaData;
        this.inicialForm = jf;
        this.fleteCurrent = fleteCurrent;
        initComponents();
        loadIcons();
        injectData();

    }

    //my methods
    private void loadIcons() {
        
        //for change icon Edit
        FontIcon iconPen = FontIcon.of(FontAwesomeSolid.PEN_SQUARE);
        iconPen.setIconSize(35);
        
        FontIcon iconPen2 = FontIcon.of(FontAwesomeSolid.PEN_SQUARE);
        iconPen2.setIconSize(35);
        iconPen2.setIconColor(ConfigManager.COLOR_BLUE);
        
        
        IconManager.setIkonliIcon(lblAddressEs, BoxiconsRegular.MAP, 20);
        IconManager.setIkonliIcon(lblEeSs, CarbonIcons.GAS_STATION, 20);
        IconManager.setIkonliIcon(lblCustomer, BootstrapIcons.PERSON, 20);
        IconManager.setIkonliIcon(lblAmount, Dashicons.MONEY_ALT, 20);
        IconManager.setIkonliIcon(lblVolume, FontAwesomeSolid.HAND_HOLDING_WATER, 20);
        IconManager.setIkonliIcon(lblStatus, BootstrapIcons.CASH, 20);

        btnEditar1.setBorderPainted(false);   // Quita el borde
        btnEditar1.setContentAreaFilled(false); // Quita el fondo gris
        btnEditar1.setFocusPainted(false);    // Quita el cuadro de selección
        btnEditar1.setMargin(new Insets(0, 0, 0, 0)); // Ajusta el botón al borde del icono
        btnEditar1.setIcon(iconPen);
        btnEditar1.setRolloverIcon(iconPen2);
    }

    public void injectData() {
        // --- CABECERA (Datos del LoadDTO) ---
        lblCustomer.setText(cargaData.getNameCustomer());
        lblEeSs.setText(cargaData.getNameEESS());
        lblAddressEs.setText(cargaData.getAddressEESS());
        lblAmount.setText("s/ " + String.valueOf( (int) cargaData.getAmount()));
        colorStatus();
        // Aquí recorremos los detalles que YA viven dentro del objeto
        for (LoadDetailDTO det : cargaData.getDetails()) {
            if (det.getProductName().equalsIgnoreCase("DB5")) {
                lblDB5.setText(det.getProductName() + ": " + (int) det.getVolume());
            }

            if (det.getProductName().equalsIgnoreCase("G. Premiun")) {
                lblPremiun.setText(det.getProductName() + ": " + (int) det.getVolume());
            }

            if (det.getProductName().equalsIgnoreCase("G. Regular")) {
                lblRegular.setText(det.getProductName() + ": " + (int) det.getVolume());
            }

        }
    }

    public void colorStatus() {

        String status = cargaData.getPaymentStatus();
        if (status.equalsIgnoreCase("Pagado")) {
            lblStatus.setForeground(new Color(40, 167, 69));
            lblStatus.setText("  "+status);
        } else if (status.equalsIgnoreCase("Pendiente")) {
            lblStatus.setForeground(new Color(220, 53, 69));
            lblStatus.setText("  "+status);
        } else if (status.equalsIgnoreCase("Adelanto")) {
            lblStatus.setForeground(new Color(70, 130, 180));
            lblStatus.setText("  "+status);
           
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomer = new javax.swing.JLabel();
        lblEeSs = new javax.swing.JLabel();
        lblAddressEs = new javax.swing.JLabel();
        lblVolume = new javax.swing.JLabel();
        lblDB5 = new javax.swing.JLabel();
        lblPremiun = new javax.swing.JLabel();
        lblRegular = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnEditar1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(188, 260));
        setPreferredSize(new java.awt.Dimension(188, 260));

        lblCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCustomer.setText("Erika Marizaaa");

        lblEeSs.setText("Sol de oro");

        lblAddressEs.setText("Santa ana");

        lblVolume.setText("Volumen (gl):");

        lblDB5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDB5.setText("-");

        lblPremiun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPremiun.setText("-");

        lblRegular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRegular.setText("-");

        lblAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAmount.setText("s/ ");

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatus.setText("-");

        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEeSs)
                            .addComponent(lblCustomer)
                            .addComponent(lblVolume)
                            .addComponent(lblAddressEs)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAmount)
                                        .addGap(0, 103, Short.MAX_VALUE))
                                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPremiun)
                            .addComponent(lblRegular)
                            .addComponent(lblDB5))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEeSs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAddressEs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVolume)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDB5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPremiun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRegular)
                        .addGap(8, 8, 8)
                        .addComponent(lblAmount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatus)))
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed

        OptionsLoad w = new OptionsLoad(cargaData);

        w.setLocationRelativeTo(this); // Centrar
        w.setResizable(false);        // No redimensionar
        w.setVisible(true);            //mostrar

        try {

            List<LoadDTO> ll = inicialForm.loadListLoadsWithDetails(fleteCurrent);
            inicialForm.refreshCardsLoads(ll);
            inicialForm.loadFinanceGlobal();
            inicialForm.loadFinanceFlete();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        } finally {
        }


    }//GEN-LAST:event_btnEditar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar1;
    private javax.swing.JLabel lblAddressEs;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDB5;
    private javax.swing.JLabel lblEeSs;
    private javax.swing.JLabel lblPremiun;
    private javax.swing.JLabel lblRegular;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblVolume;
    // End of variables declaration//GEN-END:variables
}
